 - echo "Rules in database:" $(sqlite3 "$DATABASE_PATH" "SELECT COUNT(*) FROM rules;" 2>/dev/null || echo "0")

# ============================================================================
# YARA Rule Validation Pipeline - SIMPLIFIED
# ============================================================================

variables:
  PYTHON_IMAGE: "python:3.11-slim"
  YARA_ROOT: "Yara Rules"
  NEW_RULES_DIR: "Yara Rules/New_Rules"
  BASELINE_DIR: "Yara Rules/Baseline_Rules"
  REJECTED_DIR: "Yara Rules/Rejected_Rules"
  DATABASE_PATH: "Yara Rules/database/yara_rules.db"
  REPORTS_DIR: "Yara Rules/reports"
  TEMP_DIR: "Yara Rules/temp"
  TOOLS_DIR: "Yara Rules/Tools"

stages:
  - validate
  - commit

# ============================================================================
# Workflow Rules
# ============================================================================
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE !~ /\[skip ci\]/'
      changes:
        - "Yara Rules/New_Rules/**/*"
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "api"'

# ============================================================================
# STAGE 1: Validate Everything (One Big Job)
# ============================================================================
validate_and_integrate:
  stage: validate
  image: $PYTHON_IMAGE
  tags:
    - yaralyzer
  script:
    - echo "================================================================================"
    - echo "🚀 YARA Rule Validation Pipeline"
    - echo "================================================================================"
    
    # Install dependencies
    - apt-get update -qq && apt-get install -y -qq git sqlite3
    - pip3 install --quiet --break-system-packages yara-python 2>/dev/null || pip3 install --quiet yara-python
    
    # Create directories
    - mkdir -p "$REPORTS_DIR" "$TEMP_DIR" "$REJECTED_DIR"
    
    # ========================================================================
    # STEP 1: Baseline Check
    # ========================================================================
    - echo ""
    - echo "🔍 STEP 1: Checking rules against baseline database..."
    - echo "------------------------------------------------------------------------"
    
    - |
      RULE_COUNT=$(find "$NEW_RULES_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      echo "Found $RULE_COUNT rule file(s) in $NEW_RULES_DIR"
      
      if [ "$RULE_COUNT" -eq 0 ]; then
        echo "ℹ️  No YARA rules found - exiting"
        exit 0
      fi
    
    - echo "Database state BEFORE processing:"
    - ls -lh "$DATABASE_PATH"
    - sqlite3 "$DATABASE_PATH" "SELECT COUNT(*) FROM rules;" 2>/dev/null | xargs -I {} echo "Rules in database: {}"
    
    - |
      python3 "$TOOLS_DIR/check_baseline.py" "$NEW_RULES_DIR" \
        --database "$DATABASE_PATH" \
        --output-new "$TEMP_DIR/new_rules" \
        --output-existing "$TEMP_DIR/already_in_baseline" \
        --json-report "$REPORTS_DIR/baseline_check.json" \
        --verbose
    
    - |
      if [ ! -d "$TEMP_DIR/new_rules" ] || [ -z "$(ls -A "$TEMP_DIR/new_rules" 2>/dev/null)" ]; then
        echo "ℹ️  No new rules to validate (all already in baseline)"
        echo '{"note":"all_in_baseline"}' > "$TEMP_DIR/skip_marker"
      else
        NEW_COUNT=$(find "$TEMP_DIR/new_rules" -type f | wc -l)
        echo "✅ Found $NEW_COUNT new rule(s) to validate"
      fi
    
    # ========================================================================
    # STEP 2: Syntax Validation
    # ========================================================================
    - echo ""
    - echo "✅ STEP 2: Validating YARA syntax..."
    - echo "------------------------------------------------------------------------"
    
    - |
      if [ -f "$TEMP_DIR/skip_marker" ]; then
        echo "ℹ️  Skipping - no new rules"
      else
        python3 "$TOOLS_DIR/validate_syntax.py" "$TEMP_DIR/new_rules" \
          --output-valid "$TEMP_DIR/syntax_valid" \
          --output-failed "$REJECTED_DIR" \
          --json-report "$REPORTS_DIR/syntax_validation.json" \
          --verbose
        
        if [ ! -d "$TEMP_DIR/syntax_valid" ] || [ -z "$(ls -A "$TEMP_DIR/syntax_valid" 2>/dev/null)" ]; then
          echo "❌ No rules passed syntax validation"
          echo '{"note":"no_syntax_valid"}' > "$TEMP_DIR/skip_marker"
        else
          VALID_COUNT=$(find "$TEMP_DIR/syntax_valid" -type f | wc -l)
          echo "✅ $VALID_COUNT rule(s) passed syntax validation"
        fi
      fi
    
    # ========================================================================
    # STEP 3: Metadata Validation
    # ========================================================================
    - echo ""
    - echo "📋 STEP 3: Validating metadata..."
    - echo "------------------------------------------------------------------------"
    
    - |
      if [ -f "$TEMP_DIR/skip_marker" ]; then
        echo "ℹ️  Skipping - no rules to validate"
      else
        python3 "$TOOLS_DIR/validate_metadata.py" "$TEMP_DIR/syntax_valid" \
          --move-invalid "$REJECTED_DIR" \
          --json-report "$REPORTS_DIR/metadata_validation.json" \
          --verbose
        
        if [ ! -d "$TEMP_DIR/syntax_valid" ] || [ -z "$(ls -A "$TEMP_DIR/syntax_valid" 2>/dev/null)" ]; then
          echo "❌ No rules passed metadata validation"
          echo '{"note":"no_metadata_valid"}' > "$TEMP_DIR/skip_marker"
        else
          VALID_COUNT=$(find "$TEMP_DIR/syntax_valid" -type f | wc -l)
          echo "✅ $VALID_COUNT rule(s) passed metadata validation"
        fi
      fi
    
    # ========================================================================
    # STEP 4: Deduplication
    # ========================================================================
    - echo ""
    - echo "🔄 STEP 4: Deduplicating rules..."
    - echo "------------------------------------------------------------------------"
    
    - |
      if [ -f "$TEMP_DIR/skip_marker" ]; then
        echo "ℹ️  Skipping - no rules to deduplicate"
      else
        python3 "$TOOLS_DIR/deduplicate_rules.py" "$TEMP_DIR/syntax_valid" \
          --output-dir "$TEMP_DIR/deduplicated" \
          --json-report "$REPORTS_DIR/deduplication.json" \
          --verbose
        
        if [ ! -d "$TEMP_DIR/deduplicated" ] || [ -z "$(ls -A "$TEMP_DIR/deduplicated" 2>/dev/null)" ]; then
          echo "❌ No rules remain after deduplication"
          echo '{"note":"no_deduplicated"}' > "$TEMP_DIR/skip_marker"
        else
          DEDUP_COUNT=$(find "$TEMP_DIR/deduplicated" -type f | wc -l)
          echo "✅ $DEDUP_COUNT rule(s) after deduplication"
        fi
      fi
    
    # ========================================================================
    # STEP 5: Update Database & Move to Baseline
    # ========================================================================
    - echo ""
    - echo "💾 STEP 5: Updating database and moving to baseline..."
    - echo "------------------------------------------------------------------------"
    
    - |
      if [ -f "$TEMP_DIR/skip_marker" ]; then
        echo "ℹ️  No rules to add to database"
        echo '{"timestamp":"'$(date -Iseconds)'","statistics":{"total_added":0,"total_skipped":0},"added_rules":[],"skipped_rules":[]}' > "$REPORTS_DIR/database_update.json"
      else
        echo "📊 Updating database..."
        python3 "$TOOLS_DIR/update_database.py" "$TEMP_DIR/deduplicated" \
          --database "$DATABASE_PATH" \
          --json-report "$REPORTS_DIR/database_update.json" \
          --verbose
        
        echo ""
        echo "Database state AFTER update:"
        ls -lh "$DATABASE_PATH"
        sqlite3 "$DATABASE_PATH" "SELECT COUNT(*) FROM rules;" 2>/dev/null | xargs -I {} echo "Rules in database: {}"
        
        echo ""
        echo "📁 Moving validated rules to baseline..."
        mkdir -p "$BASELINE_DIR"
        
        for file in "$TEMP_DIR/deduplicated"/*; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo "  Moving: $filename"
            cp "$file" "$BASELINE_DIR/$filename"
          fi
        done
        
        MOVED_COUNT=$(find "$BASELINE_DIR" -type f -newer "$TEMP_DIR/deduplicated" 2>/dev/null | wc -l)
        echo "✅ Moved $MOVED_COUNT rule(s) to baseline"
      fi
    
    # ========================================================================
    # STEP 6: Generate Reports
    # ========================================================================
    - echo ""
    - echo "📊 STEP 6: Generating comprehensive report..."
    - echo "------------------------------------------------------------------------"
    
    - |
      python3 "$TOOLS_DIR/generate_report.py" \
        --baseline "$REPORTS_DIR/baseline_check.json" \
        --syntax "$REPORTS_DIR/syntax_validation.json" \
        --metadata "$REPORTS_DIR/metadata_validation.json" \
        --dedup "$REPORTS_DIR/deduplication.json" \
        --database "$REPORTS_DIR/database_update.json" \
        --output-json "$YARA_ROOT/validation_report.json" \
        --output-markdown "$YARA_ROOT/validation_report.md"
    
    - echo "✅ Reports generated at:"
    - echo "  - $YARA_ROOT/validation_report.json"
    - echo "  - $YARA_ROOT/validation_report.md"
    
    # ========================================================================
    # STEP 7: Show Summary
    # ========================================================================
    - echo ""
    - echo "================================================================================"
    - echo "📊 VALIDATION SUMMARY"
    - echo "================================================================================"
    - |
      ADDED=0
      REJECTED=0
      
      if [ -d "$BASELINE_DIR" ]; then
        ADDED=$(find "$BASELINE_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) -newer "$TEMP_DIR" 2>/dev/null | wc -l)
      fi
      
      if [ -d "$REJECTED_DIR" ]; then
        REJECTED=$(find "$REJECTED_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      fi
      
      echo "✅ Rules Added to Baseline: $ADDED"
      echo "❌ Rules Rejected: $REJECTED"
      echo "📊 Database Updated: YES"
      echo "📄 Reports Generated: YES"
    - echo "================================================================================"
  
  artifacts:
    paths:
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 2: Commit Everything
# ============================================================================
commit_changes:
  stage: commit
  image: $PYTHON_IMAGE
  tags:
    - yaralyzer
  needs:
    - job: validate_and_integrate
      artifacts: true
  script:
    - echo "================================================================================"
    - echo "🧹 COMMITTING CHANGES"
    - echo "================================================================================"
    
    # Install git
    - apt-get update -qq && apt-get install -y -qq git
    
    # Configure Git
    - git config --global user.email "${user_email}"
    - git config --global user.name "${user_name}"
    - git config --global http.sslCAInfo "${SSL_CERT_FILE_PATH}"
    - git remote set-url origin https://alesher:${PAT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    
    # Fetch and check status
    - git fetch origin $CI_COMMIT_REF_NAME
    - |
      BEHIND=$(git rev-list --count HEAD..origin/$CI_COMMIT_REF_NAME)
      if [ "$BEHIND" -gt 0 ]; then
        echo "⚠️  Branch is $BEHIND commit(s) behind - rebasing..."
        git rebase origin/$CI_COMMIT_REF_NAME
      fi
    
    # Remove processed rules from New_Rules
    - echo ""
    - echo "🗑️  Removing processed rules from $NEW_RULES_DIR..."
    - |
      REMOVED_COUNT=0
      for file in "$NEW_RULES_DIR"/*.yar "$NEW_RULES_DIR"/*.yara "$NEW_RULES_DIR"/*.rule; do
        if [ -f "$file" ]; then
          echo "  Removing: $(basename "$file")"
          git rm -f "$file"
          REMOVED_COUNT=$((REMOVED_COUNT + 1))
        fi
      done
      echo "Removed $REMOVED_COUNT file(s)"
    
    # Stage all changes
    - echo ""
    - echo "📝 Staging all changes..."
    - git add "$YARA_ROOT/"
    
    # Show what will be committed
    - echo ""
    - echo "📋 Changes to commit:"
    - git status --short
    - echo ""
    - git diff --cached --stat
    
    # Commit and push
    - |
      if ! git diff --cached --quiet; then
        ADDED=$(git diff --cached --name-only | grep -c "$BASELINE_DIR" || echo "0")
        REJECTED=$(git diff --cached --name-only | grep -c "$REJECTED_DIR" || echo "0")
        
        if [ "$ADDED" -gt 0 ] && [ "$REJECTED" -gt 0 ]; then
          COMMIT_MSG="CI: Processed YARA rules - Added: ${ADDED}, Rejected: ${REJECTED} [skip ci]"
        elif [ "$ADDED" -gt 0 ]; then
          COMMIT_MSG="CI: Successfully added ${ADDED} YARA rule(s) [skip ci]"
        elif [ "$REJECTED" -gt 0 ]; then
          COMMIT_MSG="CI: Rejected ${REJECTED} YARA rule(s) [skip ci]"
        else
          COMMIT_MSG="CI: Updated YARA rules [skip ci]"
        fi
        
        echo "💬 Commit message: $COMMIT_MSG"
        git commit -m "$COMMIT_MSG"
        
        echo ""
        echo "📤 Pushing to $CI_COMMIT_REF_NAME..."
        git push origin HEAD:${CI_COMMIT_REF_NAME}
        
        echo ""
        echo "✅ Successfully pushed changes"
      else
        echo "ℹ️  No changes to commit"
      fi
    
    - echo ""
    - echo "================================================================================"
    - echo "✅ PIPELINE COMPLETED"
    - echo "================================================================================"
  
  allow_failure: false
