# ============================================================================
# YARA Rule Validation Pipeline
# ============================================================================

variables:
  PYTHON_IMAGE: "python:3.11-slim"
  YARA_ROOT: "Yara Rules"
  NEW_RULES_DIR: "Yara Rules/New_Rules"
  BASELINE_DIR: "Yara Rules/Baseline_Rules"
  REJECTED_DIR: "Yara Rules/Rejected_Rules"
  DATABASE_PATH: "Yara Rules/database/yara_rules.db"
  REPORTS_DIR: "Yara Rules/reports"
  TEMP_DIR: "Yara Rules/temp"
  TOOLS_DIR: "Yara Rules/Tools"
  GIT_STRATEGY: none

stages:
  - check_baseline
  - validate_syntax
  - validate_metadata
  - deduplicate
  - integrate
  - report
  - cleanup

# ============================================================================
# Workflow Rules
# ============================================================================
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE !~ /\[skip ci\]/'
      changes:
        - "Yara Rules/New_Rules/**/*"
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "api"'

# ============================================================================
# Reusable Configuration
# ============================================================================
.python_setup: &python_setup
  tags:
    - yaralyzer
  before_script:
    - echo "🐍 Setting up Python environment..."
    - pip3 install --quiet --break-system-packages yara-python 2>/dev/null || pip3 install --quiet yara-python
    - python3 --version
    - echo "✅ Python environment ready"

# ============================================================================
# STAGE 1: Baseline Check
# ============================================================================
baseline_check:
  stage: check_baseline
  image: $PYTHON_IMAGE
  variables:
    GIT_STRATEGY: clone
  <<: *python_setup
  script:
    - echo "🔍 Stage 1: Checking rules against baseline database"
    - mkdir -p "$REPORTS_DIR" "$TEMP_DIR"
    
    # Check if there are any rules to process
    - |
      RULE_COUNT=$(find "$NEW_RULES_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      echo "Found $RULE_COUNT rule file(s)"
      
      if [ "$RULE_COUNT" -eq 0 ]; then
        echo "ℹ️  No YARA rules found in $NEW_RULES_DIR"
        # Create empty marker files so subsequent jobs can detect this
        mkdir -p "$TEMP_DIR"
        touch "$TEMP_DIR/no_rules_found"
        exit 0
      fi
    
    # Run baseline check
    - |
      python3 "$TOOLS_DIR/check_baseline.py" "$NEW_RULES_DIR" \
        --database "$DATABASE_PATH" \
        --output-new "$TEMP_DIR/new_rules" \
        --output-existing "$TEMP_DIR/already_in_baseline" \
        --json-report "$REPORTS_DIR/baseline_check.json" \
        --verbose
    
    # Check results
    - |
      echo "📊 Baseline check results:"
      if [ -d "$TEMP_DIR/new_rules" ]; then
        NEW_COUNT=$(find "$TEMP_DIR/new_rules" -type f 2>/dev/null | wc -l)
        echo "  - New rules: $NEW_COUNT"
      else
        echo "  - New rules: 0"
      fi
      
      if [ -d "$TEMP_DIR/already_in_baseline" ]; then
        EXISTING_COUNT=$(find "$TEMP_DIR/already_in_baseline" -type f 2>/dev/null | wc -l)
        echo "  - Already in baseline: $EXISTING_COUNT"
      else
        echo "  - Already in baseline: 0"
      fi
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 2: Syntax Validation
# ============================================================================
validate_syntax:
  stage: validate_syntax
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: baseline_check
      artifacts: true
  script:
    - echo "✅ Stage 2: Validating YARA syntax"
    
    # Check if we have new rules to validate
    - |
      if [ -f "$TEMP_DIR/no_rules_found" ]; then
        echo "ℹ️  No rules to validate (marker file found)"
        exit 0
      fi
      
      if [ ! -d "$TEMP_DIR/new_rules" ] || [ -z "$(ls -A "$TEMP_DIR/new_rules" 2>/dev/null)" ]; then
        echo "ℹ️  No new rules to validate (all already in baseline)"
        mkdir -p "$TEMP_DIR"
        touch "$TEMP_DIR/no_new_rules"
        exit 0
      fi
    
    - mkdir -p "$REJECTED_DIR"
    
    - |
      python3 "$TOOLS_DIR/validate_syntax.py" "$TEMP_DIR/new_rules" \
        --output-valid "$TEMP_DIR/syntax_valid" \
        --output-failed "$REJECTED_DIR" \
        --json-report "$REPORTS_DIR/syntax_validation.json" \
        --verbose
    
    # Check results
    - |
      if [ -d "$TEMP_DIR/syntax_valid" ]; then
        VALID_COUNT=$(find "$TEMP_DIR/syntax_valid" -type f 2>/dev/null | wc -l)
        echo "✅ $VALID_COUNT rule(s) passed syntax validation"
      else
        echo "❌ No rules passed syntax validation"
      fi
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 3: Metadata Validation
# ============================================================================
validate_metadata:
  stage: validate_metadata
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: validate_syntax
      artifacts: true
  script:
    - echo "📋 Stage 3: Validating metadata"
    
    # Check if we have rules to validate
    - |
      if [ -f "$TEMP_DIR/no_rules_found" ] || [ -f "$TEMP_DIR/no_new_rules" ]; then
        echo "ℹ️  No rules to validate (marker file found)"
        exit 0
      fi
      
      if [ ! -d "$TEMP_DIR/syntax_valid" ] || [ -z "$(ls -A "$TEMP_DIR/syntax_valid" 2>/dev/null)" ]; then
        echo "ℹ️  No rules to validate (none passed syntax check)"
        mkdir -p "$TEMP_DIR"
        touch "$TEMP_DIR/no_syntax_valid"
        exit 0
      fi
    
    - |
      python3 "$TOOLS_DIR/validate_metadata.py" "$TEMP_DIR/syntax_valid" \
        --move-invalid "$REJECTED_DIR" \
        --json-report "$REPORTS_DIR/metadata_validation.json" \
        --verbose
    
    # Check results
    - |
      if [ -d "$TEMP_DIR/syntax_valid" ]; then
        VALID_COUNT=$(find "$TEMP_DIR/syntax_valid" -type f 2>/dev/null | wc -l)
        echo "✅ $VALID_COUNT rule(s) passed metadata validation"
      else
        echo "❌ No rules passed metadata validation"
      fi
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 4: Deduplication
# ============================================================================
deduplicate:
  stage: deduplicate
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: validate_metadata
      artifacts: true
  script:
    - echo "🔄 Stage 4: Deduplicating rules"
    
    # Check if we have rules to deduplicate
    - |
      if [ -f "$TEMP_DIR/no_rules_found" ] || [ -f "$TEMP_DIR/no_new_rules" ] || [ -f "$TEMP_DIR/no_syntax_valid" ]; then
        echo "ℹ️  No rules to deduplicate (marker file found)"
        exit 0
      fi
      
      if [ ! -d "$TEMP_DIR/syntax_valid" ] || [ -z "$(ls -A "$TEMP_DIR/syntax_valid" 2>/dev/null)" ]; then
        echo "ℹ️  No rules to deduplicate (none passed metadata check)"
        mkdir -p "$TEMP_DIR"
        touch "$TEMP_DIR/no_metadata_valid"
        exit 0
      fi
    
    - |
      python3 "$TOOLS_DIR/deduplicate_rules.py" "$TEMP_DIR/syntax_valid" \
        --output-dir "$TEMP_DIR/deduplicated" \
        --json-report "$REPORTS_DIR/deduplication.json" \
        --verbose
    
    # Check results
    - |
      if [ -d "$TEMP_DIR/deduplicated" ]; then
        DEDUP_COUNT=$(find "$TEMP_DIR/deduplicated" -type f 2>/dev/null | wc -l)
        echo "✅ $DEDUP_COUNT rule(s) after deduplication"
      else
        echo "❌ No rules remain after deduplication"
      fi
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 5: Database Update & Integration
# ============================================================================
integrate:
  stage: integrate
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: deduplicate
      artifacts: true
  script:
    - echo "💾 Stage 5: Updating database and integrating rules"
    
    # Check if we have rules to integrate
    - |
      if [ -f "$TEMP_DIR/no_rules_found" ]; then
        echo "ℹ️  No rules to integrate"
        mkdir -p "$REPORTS_DIR"
        echo '{"timestamp":"'$(date -Iseconds)'","statistics":{"total_added":0,"total_skipped":0},"added_rules":[],"skipped_rules":[]}' > "$REPORTS_DIR/database_update.json"
        exit 0
      fi
      
      if [ -f "$TEMP_DIR/no_new_rules" ]; then
        echo "ℹ️  All rules already in baseline - no database update needed"
        mkdir -p "$REPORTS_DIR"
        echo '{"timestamp":"'$(date -Iseconds)'","statistics":{"total_added":0,"total_skipped":0},"added_rules":[],"skipped_rules":[],"note":"all rules already in baseline"}' > "$REPORTS_DIR/database_update.json"
        exit 0
      fi
      
      if [ ! -d "$TEMP_DIR/deduplicated" ] || [ -z "$(ls -A "$TEMP_DIR/deduplicated" 2>/dev/null)" ]; then
        echo "ℹ️  No validated rules to add to database"
        mkdir -p "$REPORTS_DIR"
        echo '{"timestamp":"'$(date -Iseconds)'","statistics":{"total_added":0,"total_skipped":0},"added_rules":[],"skipped_rules":[],"note":"no rules passed validation"}' > "$REPORTS_DIR/database_update.json"
        exit 0
      fi
    
    # We have rules to process!
    - echo "📊 Updating baseline database..."
    - |
      python3 "$TOOLS_DIR/update_database.py" "$TEMP_DIR/deduplicated" \
        --database "$DATABASE_PATH" \
        --json-report "$REPORTS_DIR/database_update.json" \
        --verbose
    
    - echo "📁 Moving validated rules to baseline..."
    - mkdir -p "$BASELINE_DIR"
    - cp -v "$TEMP_DIR/deduplicated"/* "$BASELINE_DIR/"
    
    - echo "✅ Integration complete"
  
  artifacts:
    paths:
      - "$BASELINE_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$DATABASE_PATH"
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 6: Generate Report
# ============================================================================
generate_report:
  stage: report
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: integrate
      artifacts: true
  script:
    - echo "📊 Stage 6: Generating comprehensive validation report"
    
    - |
      python3 "$TOOLS_DIR/generate_report.py" \
        --baseline "$REPORTS_DIR/baseline_check.json" \
        --syntax "$REPORTS_DIR/syntax_validation.json" \
        --metadata "$REPORTS_DIR/metadata_validation.json" \
        --dedup "$REPORTS_DIR/deduplication.json" \
        --database "$REPORTS_DIR/database_update.json" \
        --output-json "$YARA_ROOT/validation_report.json" \
        --output-markdown "$YARA_ROOT/validation_report.md"
    
    - echo "✅ Reports generated"
  
  artifacts:
    paths:
      - "$YARA_ROOT/validation_report.json"
      - "$YARA_ROOT/validation_report.md"
      - "$REPORTS_DIR/"
      - "$BASELINE_DIR/"
      - "$REJECTED_DIR/"
      - "$DATABASE_PATH"
      - "$YARA_ROOT/"
    expire_in: 1 week

# ============================================================================
# STAGE 7: Cleanup and Commit
# ============================================================================
commit_changes:
  stage: cleanup
  image: $PYTHON_IMAGE
  tags:
    - yaralyzer
  variables:
    GIT_STRATEGY: clone
  needs:
    - job: generate_report
      artifacts: true
  script:
    - echo "🧹 Stage 7: Cleaning up and committing changes"
    
    # Configure Git
    - git config --global user.email "${user_email}"
    - git config --global user.name "${user_name}"
    - git config --global http.sslCAInfo "${SSL_CERT_FILE_PATH}"
    - git remote set-url origin https://alesher:${PAT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    
    # Sync with remote
    - git fetch origin $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    
    # Remove processed rules from New_Rules
    - echo "🗑️  Removing processed rules from $NEW_RULES_DIR..."
    - |
      REMOVED_COUNT=0
      for file in "$NEW_RULES_DIR"/*.yar "$NEW_RULES_DIR"/*.yara "$NEW_RULES_DIR"/*.rule; do
        if [ -f "$file" ]; then
          echo "  Removing: $(basename "$file")"
          git rm -f "$file" 2>/dev/null || rm -f "$file"
          REMOVED_COUNT=$((REMOVED_COUNT + 1))
        fi
      done
      echo "Removed $REMOVED_COUNT file(s)"
    
    # Stage all changes
    - git add "$BASELINE_DIR/" "$REJECTED_DIR/" "$DATABASE_PATH" "$REPORTS_DIR/" "$YARA_ROOT/validation_report"* "$NEW_RULES_DIR/" 2>/dev/null || true
    
    # Commit
    - |
      if ! git diff --cached --quiet; then
        ADDED=$(find "$BASELINE_DIR" -type f 2>/dev/null | wc -l)
        REJECTED=$(find "$REJECTED_DIR" -type f 2>/dev/null | wc -l)
        
        if [ "$ADDED" -gt 0 ] && [ "$REJECTED" -gt 0 ]; then
          MSG="CI: Processed YARA rules - Added: ${ADDED}, Rejected: ${REJECTED} [skip ci]"
        elif [ "$ADDED" -gt 0 ]; then
          MSG="CI: Successfully added ${ADDED} YARA rule(s) [skip ci]"
        elif [ "$REJECTED" -gt 0 ]; then
          MSG="CI: Rejected ${REJECTED} YARA rule(s) [skip ci]"
        else
          MSG="CI: Processed YARA rules [skip ci]"
        fi
        
        git commit -m "$MSG"
        git push origin HEAD:${CI_COMMIT_REF_NAME}
        echo "✅ Changes pushed"
      else
        echo "ℹ️  No changes to commit"
      fi
