# GitLab CI/CD Pipeline for YARA Rule Validation and Deployment

stages:
  - validate
  - integrate

variables:
  # Directories
  NEW_RULES_DIR: "Yara Rules/New Rules"
  VALIDATED_DIR: "Yara Rules/validated"
  FAILED_DIR: "Yara Rules/failed"
  BASELINE_DIR: "Yara Rules/Baseline_Rules"
  DATABASE_PATH: "Yara Rules/database/yara_rules.db"
  GIT_DEPTH: 0
  
  # Report files
  JSON_REPORT: "Yara Rules/validation_report.json"
  MD_REPORT: "Yara Rules/validation_report.md"
 
  # Python image
  PYTHON_IMAGE: "python:3.11-slim"
 
# Template for Python setup
.python_setup: &python_setup
  before_script:
    - pip3 install --quiet --no-cache-dir yara-python
    - python3 --version
    - python3 -c "import yara; print(f'YARA version: {yara.__version__}')"
 
# ==============================================================================
# STAGE 1: VALIDATE
# ==============================================================================
validate_yara_rules:
  stage: validate
  rules:
    - changes:
        - "$NEW_RULES_DIR/**"
      when: on_success
    - when: never
  image: $PYTHON_IMAGE
  <<: *python_setup
  script:
    - echo "🔍 Validating YARA rules in $NEW_RULES_DIR"
    - echo "🧹 Clearing previous failed rules"
    - rm -rf "$FAILED_DIR"
    - mkdir -p "$FAILED_DIR"
    - |
      python3 "Yara Rules/Tools/Yaralyzer.py" "$NEW_RULES_DIR" \
        --output-valid-dir "$VALIDATED_DIR" \
        --output-failed-dir "$FAILED_DIR" \
        --json-report "$JSON_REPORT" \
        --markdown-report "$MD_REPORT" \
        --deduplicate \
        --verbose \
        --require-metadata \
        --baseline-db "$DATABASE_PATH"
    - VALIDATION_EXIT_CODE=$?
    - echo "Validation exit code=$VALIDATION_EXIT_CODE"
    - echo "🧹 Cleaning up processed files from $NEW_RULES_DIR"
    - |
      FILES_BEFORE=$(find "$NEW_RULES_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) | wc -l)
      echo "📊 Files in $NEW_RULES_DIR before cleanup: $FILES_BEFORE"
    - |
      PROCESSED_FILES=""
      if [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A "$VALIDATED_DIR" 2>/dev/null)" ]; then
        echo "✅ Found validated files:"
        for file in "$VALIDATED_DIR"/*; do
          [ -f "$file" ] || continue
          basename_file=$(basename "$file")
          original_name=$(grep "^// Source:" "$file" 2>/dev/null | sed 's/.*\///' || echo "$basename_file")
          if [ -z "$original_name" ]; then
            original_name="$basename_file"
          fi
          echo "  - $original_name"
          PROCESSED_FILES="$PROCESSED_FILES $original_name"
        done
      fi
    - |
      if [ -d "$FAILED_DIR" ] && [ -n "$(ls -A "$FAILED_DIR" 2>/dev/null)" ]; then
        echo "❌ Found failed files:"
        for file in "$FAILED_DIR"/*; do
          [ -f "$file" ] || continue
          basename_file=$(basename "$file")
          original_name=$(grep "^// Source:" "$file" 2>/dev/null | sed 's/.*\///' || echo "$basename_file")
          if [ -z "$original_name" ]; then
            original_name="$basename_file"
          fi
          echo "  - $original_name"
          PROCESSED_FILES="$PROCESSED_FILES $original_name"
        done
      fi
    - PROCESSED_FILES=$(echo "$PROCESSED_FILES" | tr ' ' '\n' | sort -u | tr '\n' ' ')
    - |
      if [ -n "$PROCESSED_FILES" ]; then
        echo "🗑️  Removing processed files from $NEW_RULES_DIR:"
        for filename in $PROCESSED_FILES; do
          filepath="$NEW_RULES_DIR/$filename"
          if [ -f "$filepath" ]; then
            echo "  - Removing: $filename"
            rm -f "$filepath"
          fi
        done
      else
        echo "⚠️  No processed files identified for cleanup"
      fi
    - echo "🗑️  Removing all YARA files from $NEW_RULES_DIR:"
    - find "$NEW_RULES_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) -delete
    - |
      FILES_AFTER=$(find "$NEW_RULES_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) | wc -l)
      echo "📊 Files in $NEW_RULES_DIR after cleanup: $FILES_AFTER"
      echo "📊 Files removed: $((FILES_BEFORE - FILES_AFTER))"
    - echo "📊 Remaining files in $NEW_RULES_DIR:"
    - ls -la "$NEW_RULES_DIR" || echo "Directory empty or not found"
    - exit $VALIDATION_EXIT_CODE
 
  artifacts:
    when: always
    paths:
      - $VALIDATED_DIR/
      - $FAILED_DIR/
      - $JSON_REPORT
      - $MD_REPORT
    expire_in: 7 days
 
  allow_failure: true
 
# ==============================================================================
# STAGE 2: INTEGRATE AND PUSH (COMBINED)
# ==============================================================================
integrate_and_push:
  stage: integrate
  needs:
    - job: validate_yara_rules
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - "$NEW_RULES_DIR/**"
      when: on_success
  image: $PYTHON_IMAGE
  <<: *python_setup
  script:
    - echo "📦 Starting integration and push workflow"
    
    # Verify we have artifacts to process
    - |
      FILES_TO_PROCESS=0
      [ -f "$JSON_REPORT" ] && FILES_TO_PROCESS=$((FILES_TO_PROCESS + 1))
      [ -f "$MD_REPORT" ] && FILES_TO_PROCESS=$((FILES_TO_PROCESS + 1))
      [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A "$VALIDATED_DIR" 2>/dev/null)" ] && FILES_TO_PROCESS=$((FILES_TO_PROCESS + 1))
      [ -d "$FAILED_DIR" ] && [ -n "$(ls -A "$FAILED_DIR" 2>/dev/null)" ] && FILES_TO_PROCESS=$((FILES_TO_PROCESS + 1))
      
      if [ $FILES_TO_PROCESS -eq 0 ]; then
        echo "⚠️  No files to process"
        exit 0
      fi
      
      echo "✅ Found $FILES_TO_PROCESS artifact(s) to process"
    
    # Configure Git ONCE at the beginning
    - echo "🔧 Configuring Git"
    - git config --global user.email "${user_email}"
    - git config --global user.name "${user_name}"
    - git config --global http.sslcainfo "${SSL_CERT_FILE_PATH}"
    - git remote set-url origin https://alesher:${PAT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    
    # Pull latest changes ONCE
    - echo "⬇️  Pulling latest changes"
    - git pull origin $CI_COMMIT_REF_NAME --rebase || true
    
    # ============================================================================
    # PART 1: Update Database with Validated Rules
    # ============================================================================
    - |
      if [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A "$VALIDATED_DIR" 2>/dev/null)" ]; then
        VALIDATED_COUNT=$(find "$VALIDATED_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) | wc -l)
        echo "📊 Updating database with $VALIDATED_COUNT validated rule(s)..."
        
        python3 "Yara Rules/Tools/build_rule_database.py" "$VALIDATED_DIR" \
          --database "$DATABASE_PATH" \
          --verbose || echo "⚠️  Database update had warnings (continuing)"
      else
        echo "ℹ️  No validated rules to add to database"
      fi
    
    # ============================================================================
    # PART 2: Move Validated Rules to Baseline
    # ============================================================================
    - |
      if [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A "$VALIDATED_DIR" 2>/dev/null)" ]; then
        echo "📁 Moving validated rules to baseline directory..."
        mkdir -p "$BASELINE_DIR"
        
        MOVED_COUNT=0
        for file in "$VALIDATED_DIR"/*; do
          [ -f "$file" ] || continue
          
          filename=$(basename "$file")
          dest_path="$BASELINE_DIR/$filename"
          
          # Check if file already exists in baseline
          if [ -f "$dest_path" ]; then
            echo "  ⚠️  File already exists in baseline: $filename (skipping move)"
            continue
          fi
          
          # Move the file
          cp "$file" "$dest_path"
          echo "  ✅ Copied to baseline: $filename"
          MOVED_COUNT=$((MOVED_COUNT + 1))
        done
        
        echo "📊 Total rules copied to baseline: $MOVED_COUNT"
      else
        echo "ℹ️  No validated rules to move to baseline"
      fi
    
    # ============================================================================
    # PART 3: Remove Processed Files from NEW_RULES_DIR
    # ============================================================================
    - echo "🗑️ Removing processed files from $NEW_RULES_DIR"
    - |
      REMOVED_COUNT=0
      
      # Remove validated files from NEW_RULES_DIR
      if [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A "$VALIDATED_DIR" 2>/dev/null)" ]; then
        echo "✅ Processing validated files..."
        for file in "$VALIDATED_DIR"/*; do
          [ -f "$file" ] || continue
          
          # Extract the original source filename from the header comment
          original_name=$(grep "^// Source:" "$file" 2>/dev/null | sed 's/^.*\///' | head -1)
          
          # If we can't find it in the header, fall back to the basename
          if [ -z "$original_name" ]; then
            basename_file=$(basename "$file")
            original_name=$(echo "$basename_file" | sed 's/_[0-9]\+\(\.[^.]*\)$/\1/')
          fi
          
          source_file="$NEW_RULES_DIR/$original_name"
          
          if [ -f "$source_file" ]; then
            echo "  🗑️  Removing validated: $original_name"
            git rm -f "$source_file" 2>/dev/null || rm -f "$source_file"
            REMOVED_COUNT=$((REMOVED_COUNT + 1))
          fi
        done
      fi
      
      # Remove failed files from NEW_RULES_DIR
      if [ -d "$FAILED_DIR" ] && [ -n "$(ls -A "$FAILED_DIR" 2>/dev/null)" ]; then
        echo "❌ Processing failed files..."
        for file in "$FAILED_DIR"/*; do
          [ -f "$file" ] || continue
          
          original_name=$(grep "^// Source:" "$file" 2>/dev/null | sed 's/^.*\///' | head -1)
          
          if [ -z "$original_name" ]; then
            basename_file=$(basename "$file")
            original_name=$(echo "$basename_file" | sed 's/_[0-9]\+\(\.[^.]*\)$/\1/')
          fi
          
          source_file="$NEW_RULES_DIR/$original_name"
          
          if [ -f "$source_file" ]; then
            echo "  🗑️  Removing failed: $original_name"
            git rm -f "$source_file" 2>/dev/null || rm -f "$source_file"
            REMOVED_COUNT=$((REMOVED_COUNT + 1))
          fi
        done
      fi
      
      echo "📊 Total files removed from $NEW_RULES_DIR: $REMOVED_COUNT"
    
    # ============================================================================
    # PART 4: Stage ALL Changes for Single Commit
    # ============================================================================
    - echo "📝 Staging all changes..."
    - git add "$VALIDATED_DIR/" || true
    - git add "$FAILED_DIR/" || true
    - git add "$JSON_REPORT" || true
    - git add "$MD_REPORT" || true
    - git add "$NEW_RULES_DIR/" || true
    - git add "$BASELINE_DIR/" || true
    - git add "$DATABASE_PATH" || true
    
    # Show what we're committing
    - echo "📋 Files staged for commit:"
    - git status --short
    
    # ============================================================================
    # PART 5: Single Commit and Push
    # ============================================================================
    - |
      if git diff --cached --quiet; then
        echo "⚠️  No changes to commit"
        exit 0
      fi
    
    - echo "💾 Creating single commit with all changes..."
    - |
      VALIDATED_COUNT=0
      FAILED_COUNT=0
      BASELINE_COUNT=0
      
      [ -d "$VALIDATED_DIR" ] && VALIDATED_COUNT=$(find "$VALIDATED_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      [ -d "$FAILED_DIR" ] && FAILED_COUNT=$(find "$FAILED_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      [ -d "$BASELINE_DIR" ] && BASELINE_COUNT=$(git diff --cached --name-only "$BASELINE_DIR" | wc -l)
      
      git commit -m "CI: Process YARA rules [skip ci]
      
      - Validated: ${VALIDATED_COUNT} rule(s)
      - Failed: ${FAILED_COUNT} rule(s)
      - Added to baseline: ${BASELINE_COUNT} rule(s)
      - Database updated"
      
      git commit -m "$COMMIT_MSG"
    
    - echo "📤 Pushing all changes to repository..."
    - git push origin HEAD:${CI_COMMIT_REF_NAME}
    - echo "✅ Successfully pushed all changes to ${CI_COMMIT_REF_NAME}"
  
  allow_failure: false
```

## Key Changes:

### 1. **Removed `push_to_repo` job** - merged into `integrate_and_push`

### 2. **Single workflow with 5 parts:**
   - Part 1: Update database
   - Part 2: Copy to baseline
   - Part 3: Remove from New Rules
   - Part 4: Stage all changes
   - Part 5: Single commit + push

### 3. **Git configured ONCE** at the beginning

### 4. **Pull ONCE** before making any changes

### 5. **Push ONCE** at the end with all changes

### 6. **Better commit message** showing what was processed:
```
CI: Process YARA rules [skip ci]

- Validated: 3 rule(s)
- Failed: 1 rule(s)
- Added to baseline: 3 rule(s)
- Database updated
