# GitLab CI/CD Pipeline for YARA Rule Validation and Deployment
 
stages:
  - validate
  - push
  - cleanup

variables:
  # Directories
  NEW_RULES_DIR: "Yara Rules/New Rules"
  VALIDATED_DIR: "Yara Rules/validated"
  FAILED_DIR: "Yara Rules/failed"
  BASELINE_FILE: "Yara Rules/Master_Rules_List.yar"
  GIT_DEPTH: 0
  
  # Report files
  JSON_REPORT: "Yara Rules/validation_report.json"
  MD_REPORT: "Yara Rules/validation_report.md"
 
  # Python image
  PYTHON_IMAGE: "python:3.11-slim"
 
# Template for Python setup
.python_setup:
  before_script:
    - pip3 install --quiet --no-cache-dir yara-python
    - python3 --version
    - python3 -c "import yara; print(f'YARA version: {yara.__version__}')"

# Template for Git setup
.git_setup:
  before_script:
    - git config --global user.email "${user_email}"
    - git config --global user.name "${user_name}"
    - git config --global http.sslcainfo "${SSL_CERT_FILE_PATH}"
    - git remote set-url origin https://alesher:${PAT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
 
# ==============================================================================
# STAGE 1: VALIDATE
# ==============================================================================
validate_yara_rules:
  stage: validate
  extends: .python_setup
  rules:
    - changes:
        - "$NEW_RULES_DIR/**"
      when: on_success
    - when: never
  image: $PYTHON_IMAGE
  tags:
    - yaralyzer
  script:
    - echo "🔍 Validating YARA rules in $NEW_RULES_DIR"
    - |
      python3 "Yara Rules/Tools/Yaralyzer.py" "$NEW_RULES_DIR" \
        --output-valid-dir "$VALIDATED_DIR" \
        --output-failed-dir "$FAILED_DIR" \
        --json-report "$JSON_REPORT" \
        --markdown-report "$MD_REPORT" \
        --deduplicate \
        --verbose \
        --require-metadata
 
  artifacts:
    when: always
    paths:
      - $VALIDATED_DIR/
      - $FAILED_DIR/
      - $JSON_REPORT
      - $MD_REPORT
    expire_in: 7 days
 
  allow_failure: true
 
# ==============================================================================
# STAGE 2: PUSH
# ==============================================================================
push_validated_rules:
  stage: push
  extends: .git_setup
  needs:
    - job: validate_yara_rules
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - "$NEW_RULES_DIR/**"
      when: on_success
  tags:
    - yaralyzer
  script:
    - echo "🚀 Pushing validation results to repository"
    
    # Verify we have artifacts to push
    - |
      FILES_TO_PUSH=0
      [ -f "$JSON_REPORT" ] && FILES_TO_PUSH=$((FILES_TO_PUSH + 1))
      [ -f "$MD_REPORT" ] && FILES_TO_PUSH=$((FILES_TO_PUSH + 1))
      [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A '$VALIDATED_DIR' 2>/dev/null)" ] && FILES_TO_PUSH=$((FILES_TO_PUSH + 1))
      
      if [ $FILES_TO_PUSH -eq 0 ]; then
        echo "⚠️  No files to push (validation may have failed or produced no output)"
        exit 0
      fi
      
      echo "✅ Found $FILES_TO_PUSH artifact(s) to push"
    
    # Stage validated rules and reports
    - git add "$VALIDATED_DIR/" || true
    - git add "$FAILED_DIR/" || true
    - git add "$JSON_REPORT" || true
    - git add "$MD_REPORT" || true
    
    # Show what we're committing
    - echo "📝 Files to be committed:"
    - git status --short
    
    # Check if there are changes to commit
    - |
      if git diff --cached --quiet; then
        echo "⚠️  Nothing to commit"
        exit 0
      fi
    
    # Create detailed commit message
    - |
      VALIDATED_COUNT=$(find "$VALIDATED_DIR" -type f \( -name "*.yar" -o -name "*.yara" \) 2>/dev/null | wc -l)
      FAILED_COUNT=$(find "$FAILED_DIR" -type f \( -name "*.yar" -o -name "*.yara" \) 2>/dev/null | wc -l)
      
      COMMIT_MSG="CI: Add validated YARA rules and reports [skip ci]

Summary:
- ✅ Validated: $VALIDATED_COUNT rule(s)
- ❌ Failed: $FAILED_COUNT rule(s)
- 📊 Updated validation reports

Pipeline: $CI_PIPELINE_URL"
      
      git commit -m "$COMMIT_MSG"
    
    # Push changes
    - echo "⬆️  Pushing to ${CI_COMMIT_REF_NAME}..."
    - git push origin HEAD:${CI_COMMIT_REF_NAME}
    - echo "✅ Successfully pushed validated rules and reports!"
  
  allow_failure: true

# ==============================================================================
# STAGE 3: CLEANUP
# ==============================================================================
cleanup_processed_rules:
  stage: cleanup
  extends: .git_setup
  needs:
    - job: validate_yara_rules
      artifacts: true
    - job: push_validated_rules
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - "$NEW_RULES_DIR/**"
      when: on_success
  tags:
    - yaralyzer
  script:
    - echo "🧹 Cleaning up processed rules from $NEW_RULES_DIR"
    
    # Remove validated rules from New Rules folder
    - |
      if [ -d "$VALIDATED_DIR" ] && [ -n "$(ls -A '$VALIDATED_DIR' 2>/dev/null)" ]; then
        REMOVED_COUNT=0
        echo "Processing validated rules for cleanup:"
        echo ""
        
        # Handle both .yar and .yara extensions
        for validated_file in "$VALIDATED_DIR"/*.yar "$VALIDATED_DIR"/*.yara; do
          # Skip if glob didn't match anything
          [ -f "$validated_file" ] || continue
          
          filename=$(basename "$validated_file")
          new_rules_file="$NEW_RULES_DIR/$filename"
          
          if [ -f "$new_rules_file" ]; then
            echo "  ✓ Removing: $filename"
            rm "$new_rules_file"
            REMOVED_COUNT=$((REMOVED_COUNT + 1))
          else
            echo "  ⚠️  Already removed or not found: $filename"
          fi
        done
        
        echo ""
        echo "📊 Cleanup Summary:"
        echo "   Validated rules: $(find '$VALIDATED_DIR' -type f \( -name '*.yar' -o -name '*.yara' \) 2>/dev/null | wc -l)"
        echo "   Removed from new rules: $REMOVED_COUNT"
        echo "   Remaining in new rules: $(find '$NEW_RULES_DIR' -type f \( -name '*.yar' -o -name '*.yara' \) 2>/dev/null | wc -l)"
      else
        echo "⚠️  No validated rules to clean up"
        exit 0
      fi
    
    # Stage the deletions
    - echo ""
    - echo "📦 Staging cleanup changes..."
    - git add "$NEW_RULES_DIR/"
    
    # Show what we're committing
    - echo ""
    - echo "📝 Changes to be committed:"
    - git status --short
    
    # Check if there are changes (deletions) to commit
    - |
      if git diff --cached --quiet; then
        echo "⚠️  No files were removed (already clean or no matches)"
        exit 0
      fi
    
    # Commit cleanup
    - |
      REMOVED_COUNT=$(git diff --cached --numstat | wc -l)
      
      COMMIT_MSG="CI: Cleanup processed YARA rules [skip ci]

Removed $REMOVED_COUNT successfully validated rule(s) from new rules folder.

These rules have been validated and moved to: $VALIDATED_DIR

Pipeline: $CI_PIPELINE_URL"
      
      git commit -m "$COMMIT_MSG"
    
    # Push cleanup
    - echo "⬆️  Pushing cleanup to ${CI_COMMIT_REF_NAME}..."
    - git push origin HEAD:${CI_COMMIT_REF_NAME}
    - echo "✅ Successfully cleaned up processed rules!"
  
  allow_failure: true
