# ============================================================================
# YARA Rule Validation Pipeline
# ============================================================================

variables:
  PYTHON_IMAGE: "python:3.11-slim"
  YARA_ROOT: "Yara Rules"
  NEW_RULES_DIR: "Yara Rules/New_Rules"
  BASELINE_DIR: "Yara Rules/Baseline_Rules"
  REJECTED_DIR: "Yara Rules/Rejected_Rules"
  DATABASE_PATH: "Yara Rules/database/yara_rules.db"
  REPORTS_DIR: "Yara Rules/reports"
  TEMP_DIR: "Yara Rules/temp"
  TOOLS_DIR: "Yara Rules/Tools"
  GIT_STRATEGY: none  # ← CRITICAL: Don't re-clone the repo for each job

stages:
  - check_baseline
  - validate_syntax
  - validate_metadata
  - deduplicate
  - integrate
  - report
  - cleanup

# ============================================================================
# Workflow Rules - Only run on NEW files added (not removals)
# ============================================================================
workflow:
  rules:
    # Only trigger on push when files are ADDED to New_Rules (not removed)
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE !~ /\[skip ci\]/'
      changes:
        - "Yara Rules/New_Rules/**/*"
      when: always
    # Manual triggers
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "api"'
      when: always

# ============================================================================
# Reusable Configuration
# ============================================================================
.python_setup: &python_setup
  tags:
    - yaralyzer
  before_script:
    - echo "🐍 Setting up Python environment..."
    - pip3 install --quiet --break-system-packages yara-python 2>/dev/null || pip3 install --quiet yara-python
    - python3 --version
    - echo "✅ Python environment ready"

# ============================================================================
# STAGE 1: Baseline Check (Filter existing rules)
# ============================================================================
baseline_check:
  stage: check_baseline
  image: $PYTHON_IMAGE
  variables:
    GIT_STRATEGY: clone  # ← Only this first job needs to clone
  <<: *python_setup
  script:
    - echo "🔍 Stage 1: Checking rules against baseline database"
    - mkdir -p "$REPORTS_DIR" "$TEMP_DIR"
    
    # Check if there are any rules to process
    - |
      RULE_COUNT=$(find "$NEW_RULES_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      if [ "$RULE_COUNT" -eq 0 ]; then
        echo "ℹ️  No YARA rules found in $NEW_RULES_DIR"
        echo "SKIP_PIPELINE=true" > pipeline.env
        echo "HAS_NEW_RULES=false" >> pipeline.env
        echo "HAS_EXISTING_RULES=false" >> pipeline.env
        echo "EXISTING_COUNT=0" >> pipeline.env
        exit 0
      else
        echo "📋 Found $RULE_COUNT rule file(s) to process"
        echo "SKIP_PIPELINE=false" > pipeline.env
      fi
    
    # Run baseline check
    - |
      python3 "$TOOLS_DIR/check_baseline.py" "$NEW_RULES_DIR" \
        --database "$DATABASE_PATH" \
        --output-new "$TEMP_DIR/new_rules" \
        --output-existing "$TEMP_DIR/already_in_baseline" \
        --json-report "$REPORTS_DIR/baseline_check.json" \
        --verbose
    
    # Check if we have any NEW rules to validate
    - |
      if [ -d "$TEMP_DIR/new_rules" ] && [ -n "$(ls -A "$TEMP_DIR/new_rules" 2>/dev/null)" ]; then
        NEW_COUNT=$(find "$TEMP_DIR/new_rules" -type f | wc -l)
        echo "✅ Found $NEW_COUNT new rule(s) - proceeding to validation"
        echo "HAS_NEW_RULES=true" >> pipeline.env
      else
        echo "ℹ️  No new rules to validate (all already in baseline)"
        echo "HAS_NEW_RULES=false" >> pipeline.env
      fi
    
    # Check if we have rules that are already in baseline
    - |
      if [ -d "$TEMP_DIR/already_in_baseline" ] && [ -n "$(ls -A "$TEMP_DIR/already_in_baseline" 2>/dev/null)" ]; then
        EXISTING_COUNT=$(find "$TEMP_DIR/already_in_baseline" -type f | wc -l)
        echo "⏭️  Found $EXISTING_COUNT rule(s) already in baseline"
        echo "HAS_EXISTING_RULES=true" >> pipeline.env
        echo "EXISTING_COUNT=$EXISTING_COUNT" >> pipeline.env
      else
        echo "HAS_EXISTING_RULES=false" >> pipeline.env
        echo "EXISTING_COUNT=0" >> pipeline.env
      fi
    
    # Show what we captured
    - echo "📋 Pipeline environment variables:"
    - cat pipeline.env
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"  # ← Include entire Yara Rules directory
      - pipeline.env  # ← Explicit path
    reports:
      dotenv: pipeline.env
    expire_in: 1 week

# ============================================================================
# STAGE 2: Syntax Validation
# ============================================================================
validate_syntax:
  stage: validate_syntax
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: baseline_check
      artifacts: true
  rules:
    - if: $HAS_NEW_RULES == "true"
      when: on_success
    - when: never
  script:
    - echo "✅ Stage 2: Validating YARA syntax"
    - echo "📋 Current environment:"
    - cat pipeline.env || echo "⚠️  pipeline.env not found"
    - mkdir -p "$REJECTED_DIR"
    
    - |
      python3 "$TOOLS_DIR/validate_syntax.py" "$TEMP_DIR/new_rules" \
        --output-valid "$TEMP_DIR/syntax_valid" \
        --output-failed "$REJECTED_DIR" \
        --json-report "$REPORTS_DIR/syntax_validation.json" \
        --verbose
    
    # Check if we have any valid rules after syntax check
    - |
      if [ -d "$TEMP_DIR/syntax_valid" ] && [ -n "$(ls -A "$TEMP_DIR/syntax_valid" 2>/dev/null)" ]; then
        VALID_COUNT=$(find "$TEMP_DIR/syntax_valid" -type f | wc -l)
        echo "✅ $VALID_COUNT rule(s) passed syntax validation"
        echo "HAS_SYNTAX_VALID=true" >> pipeline.env
      else
        echo "❌ No rules passed syntax validation"
        echo "HAS_SYNTAX_VALID=false" >> pipeline.env
      fi
    
    - echo "📋 Updated environment:"
    - cat pipeline.env
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
      - pipeline.env
    reports:
      dotenv: pipeline.env
    expire_in: 1 week

# ============================================================================
# STAGE 3: Metadata Validation
# ============================================================================
validate_metadata:
  stage: validate_metadata
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: validate_syntax
      artifacts: true
  rules:
    - if: $HAS_SYNTAX_VALID == "true"
      when: on_success
    - when: never
  script:
    - echo "📋 Stage 3: Validating metadata"
    - echo "📋 Current environment:"
    - cat pipeline.env || echo "⚠️  pipeline.env not found"
    
    - |
      python3 "$TOOLS_DIR/validate_metadata.py" "$TEMP_DIR/syntax_valid" \
        --move-invalid "$REJECTED_DIR" \
        --json-report "$REPORTS_DIR/metadata_validation.json" \
        --verbose
    
    # Re-check what's still in syntax_valid (metadata check removes invalid files)
    - |
      if [ -d "$TEMP_DIR/syntax_valid" ] && [ -n "$(ls -A "$TEMP_DIR/syntax_valid" 2>/dev/null)" ]; then
        VALID_COUNT=$(find "$TEMP_DIR/syntax_valid" -type f | wc -l)
        echo "✅ $VALID_COUNT rule(s) passed metadata validation"
        echo "HAS_METADATA_VALID=true" >> pipeline.env
      else
        echo "❌ No rules passed metadata validation"
        echo "HAS_METADATA_VALID=false" >> pipeline.env
      fi
    
    - echo "📋 Updated environment:"
    - cat pipeline.env
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
      - pipeline.env
    reports:
      dotenv: pipeline.env
    expire_in: 1 week

# ============================================================================
# STAGE 4: Deduplication
# ============================================================================
deduplicate:
  stage: deduplicate
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: validate_metadata
      artifacts: true
  rules:
    - if: $HAS_METADATA_VALID == "true"
      when: on_success
    - when: never
  script:
    - echo "🔄 Stage 4: Deduplicating rules"
    - echo "📋 Current environment:"
    - cat pipeline.env || echo "⚠️  pipeline.env not found"
    
    - |
      python3 "$TOOLS_DIR/deduplicate_rules.py" "$TEMP_DIR/syntax_valid" \
        --output-dir "$TEMP_DIR/deduplicated" \
        --json-report "$REPORTS_DIR/deduplication.json" \
        --verbose
    
    # Check if we have rules after deduplication
    - |
      if [ -d "$TEMP_DIR/deduplicated" ] && [ -n "$(ls -A "$TEMP_DIR/deduplicated" 2>/dev/null)" ]; then
        DEDUP_COUNT=$(find "$TEMP_DIR/deduplicated" -type f | wc -l)
        echo "✅ $DEDUP_COUNT rule(s) after deduplication"
        echo "HAS_DEDUPLICATED=true" >> pipeline.env
        echo "FINAL_VALID_COUNT=$DEDUP_COUNT" >> pipeline.env
      else
        echo "❌ No rules remain after deduplication"
        echo "HAS_DEDUPLICATED=false" >> pipeline.env
        echo "FINAL_VALID_COUNT=0" >> pipeline.env
      fi
    
    - echo "📋 Updated environment:"
    - cat pipeline.env
  
  artifacts:
    paths:
      - "$TEMP_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$YARA_ROOT/"
      - pipeline.env
    reports:
      dotenv: pipeline.env
    expire_in: 1 week

# ============================================================================
# STAGE 5: Database Update & Integration
# ============================================================================
integrate:
  stage: integrate
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: baseline_check
      artifacts: true
    - job: deduplicate
      artifacts: true
      optional: true
  rules:
    - when: on_success
  script:
    - echo "💾 Stage 5: Updating database and integrating rules"
    - echo "📋 Current environment:"
    - cat pipeline.env || echo "⚠️  pipeline.env not found - using defaults"
    
    # Source environment if it exists
    - |
      if [ -f pipeline.env ]; then
        source pipeline.env
      fi
    
    # Set defaults if not set
    - |
      HAS_DEDUPLICATED=${HAS_DEDUPLICATED:-false}
      FINAL_VALID_COUNT=${FINAL_VALID_COUNT:-0}
    
    # Update database if we have validated rules
    - |
      if [ "$HAS_DEDUPLICATED" = "true" ]; then
        echo "📊 Updating baseline database..."
        python3 "$TOOLS_DIR/update_database.py" "$TEMP_DIR/deduplicated" \
          --database "$DATABASE_PATH" \
          --json-report "$REPORTS_DIR/database_update.json" \
          --verbose
        
        echo "📁 Moving validated rules to baseline..."
        mkdir -p "$BASELINE_DIR"
        cp -v "$TEMP_DIR/deduplicated"/* "$BASELINE_DIR/" || echo "No files to copy"
      else
        echo "ℹ️  No rules to add to database"
        mkdir -p "$REPORTS_DIR"
        echo '{"timestamp":"'$(date -Iseconds)'","statistics":{"total_added":0,"total_skipped":0},"added_rules":[],"skipped_rules":[]}' > "$REPORTS_DIR/database_update.json"
      fi
  
  artifacts:
    paths:
      - "$BASELINE_DIR/"
      - "$REJECTED_DIR/"
      - "$REPORTS_DIR/"
      - "$DATABASE_PATH"
      - "$YARA_ROOT/"
      - pipeline.env
    reports:
      dotenv: pipeline.env
    expire_in: 1 week

# ============================================================================
# STAGE 6: Generate Comprehensive Report
# ============================================================================
generate_report:
  stage: report
  image: $PYTHON_IMAGE
  <<: *python_setup
  needs:
    - job: integrate
      artifacts: true
  rules:
    - when: on_success
  script:
    - echo "📊 Stage 6: Generating comprehensive validation report"
    
    - |
      python3 "$TOOLS_DIR/generate_report.py" \
        --baseline "$REPORTS_DIR/baseline_check.json" \
        --syntax "$REPORTS_DIR/syntax_validation.json" \
        --metadata "$REPORTS_DIR/metadata_validation.json" \
        --dedup "$REPORTS_DIR/deduplication.json" \
        --database "$REPORTS_DIR/database_update.json" \
        --output-json "$YARA_ROOT/validation_report.json" \
        --output-markdown "$YARA_ROOT/validation_report.md"
    
    - echo "✅ Reports generated successfully"
    - echo ""
    - echo "📄 Master Reports:"
    - echo "  - $YARA_ROOT/validation_report.json"
    - echo "  - $YARA_ROOT/validation_report.md"
  
  artifacts:
    paths:
      - "$YARA_ROOT/validation_report.json"
      - "$YARA_ROOT/validation_report.md"
      - "$REPORTS_DIR/"
      - "$BASELINE_DIR/"
      - "$REJECTED_DIR/"
      - "$DATABASE_PATH"
      - "$YARA_ROOT/"
      - pipeline.env
    expire_in: 1 week

# ============================================================================
# STAGE 7: Cleanup and Commit
# ============================================================================
commit_changes:
  stage: cleanup
  image: $PYTHON_IMAGE
  tags:
    - yaralyzer
  variables:
    GIT_STRATEGY: clone  # ← Need fresh clone for git operations
  needs:
    - job: generate_report
      artifacts: true
  rules:
    - when: on_success
  script:
    - echo "🧹 Stage 7: Cleaning up and committing changes"
    
    # Source environment variables
    - |
      if [ -f pipeline.env ]; then
        echo "📋 Loading environment:"
        cat pipeline.env
        source pipeline.env
      fi
    
    # Configure Git
    - echo "🔧 Configuring Git..."
    - git config --global user.email "${user_email}"
    - git config --global user.name "${user_name}"
    - git config --global http.sslCAInfo "${SSL_CERT_FILE_PATH}"
    - git remote set-url origin https://alesher:${PAT_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    
    # Fetch and reset to latest
    - echo "⬇️  Syncing with remote..."
    - git fetch origin $CI_COMMIT_REF_NAME
    - git reset --hard origin/$CI_COMMIT_REF_NAME
    
    # Copy artifacts back into the working directory
    - echo "📦 Restoring artifacts..."
    - |
      if [ -d "$BASELINE_DIR" ]; then
        mkdir -p "$BASELINE_DIR"
        find "$BASELINE_DIR" -type f -name "*.yar" -o -name "*.yara" -o -name "*.rule" 2>/dev/null || true
      fi
      
      if [ -d "$REJECTED_DIR" ]; then
        mkdir -p "$REJECTED_DIR"
        find "$REJECTED_DIR" -type f -name "*.yar" -o -name "*.yara" -o -name "*.rule" 2>/dev/null || true
      fi
    
    # Remove processed rules from New_Rules directory
    - echo "🗑️  Removing processed rules from $NEW_RULES_DIR..."
    - |
      REMOVED_COUNT=0
      if [ -d "$NEW_RULES_DIR" ]; then
        for file in "$NEW_RULES_DIR"/*.yar "$NEW_RULES_DIR"/*.yara "$NEW_RULES_DIR"/*.rule; do
          if [ -f "$file" ]; then
            echo "  Removing: $(basename "$file")"
            git rm -f "$file" 2>/dev/null || rm -f "$file"
            REMOVED_COUNT=$((REMOVED_COUNT + 1))
          fi
        done
      fi
      echo "🗑️  Removed $REMOVED_COUNT file(s) from $NEW_RULES_DIR"
    
    # Stage all changes
    - echo "📝 Staging changes..."
    - git add "$BASELINE_DIR/" || true
    - git add "$REJECTED_DIR/" || true
    - git add "$DATABASE_PATH" || true
    - git add "$REPORTS_DIR/" || true
    - git add "$YARA_ROOT/validation_report.json" || true
    - git add "$YARA_ROOT/validation_report.md" || true
    - git add "$NEW_RULES_DIR/" || true
    
    # Show what we're committing
    - echo "📋 Changes to commit:"
    - git status --short
    
    # Create commit message
    - |
      ADDED_COUNT=${FINAL_VALID_COUNT:-0}
      EXISTING=${EXISTING_COUNT:-0}
      
      # Count rejected files
      REJECTED_COUNT=0
      if [ -d "$REJECTED_DIR" ]; then
        REJECTED_COUNT=$(find "$REJECTED_DIR" -type f \( -name "*.yar" -o -name "*.yara" -o -name "*.rule" \) 2>/dev/null | wc -l)
      fi
      
      # Build commit message
      if [ "$ADDED_COUNT" -gt 0 ] && [ "$REJECTED_COUNT" -gt 0 ]; then
        COMMIT_MSG="CI: Processed YARA rules - Added: ${ADDED_COUNT}, Rejected: ${REJECTED_COUNT}"
      elif [ "$ADDED_COUNT" -gt 0 ]; then
        COMMIT_MSG="CI: Successfully added ${ADDED_COUNT} YARA rule(s)"
      elif [ "$REJECTED_COUNT" -gt 0 ]; then
        COMMIT_MSG="CI: Rejected ${REJECTED_COUNT} YARA rule(s)"
      elif [ "$EXISTING" -gt 0 ]; then
        COMMIT_MSG="CI: All ${EXISTING} rule(s) already in baseline"
      else
        COMMIT_MSG="CI: Processed YARA rules"
      fi
      
      # Add skip ci flag to prevent infinite loop
      COMMIT_MSG="${COMMIT_MSG} [skip ci]"
      
      echo "💬 Commit message: $COMMIT_MSG"
    
    # Commit if there are changes
    - |
      if git diff --cached --quiet; then
        echo "ℹ️  No changes to commit"
      else
        echo "💾 Creating commit..."
        git commit -m "$COMMIT_MSG"
        
        echo "📤 Pushing changes to repository..."
        git push origin HEAD:${CI_COMMIT_REF_NAME}
        
        echo "✅ Successfully pushed changes to ${CI_COMMIT_REF_NAME}"
      fi
    
    - echo ""
    - echo "================================================================================"
    - echo "✅ PIPELINE COMPLETED SUCCESSFULLY"
    - echo "================================================================================"
    - |
      echo "📊 Summary:"
      echo "  - Rules Added: ${FINAL_VALID_COUNT:-0}"
      echo "  - Rules Rejected: ${REJECTED_COUNT:-0}"
      echo "  - Already in Baseline: ${EXISTING_COUNT:-0}"
      echo ""
      echo "📄 View comprehensive report: $YARA_ROOT/validation_report.md"
      echo "================================================================================"
  
  allow_failure: false
